---
kind: pipeline
name: build

platform:
  arch: amd64

steps:
- name: set version
  image: alpine
  environment:
    VERSION: 0.${DRONE_BUILD_NUMBER}
  commands:
    - sed -i -e "s+{{VERSION}}+$VERSION+g" "config/config.json"

- name: push to registry
  image: plugins/docker
  environment:
    MYSQL_MAIN_PASSWORD:
      from_secret: mysql_main_password
    GIT_USERNAME:
      from_secret: git_username
    GIT_PASSWORD:
      from_secret: git_password
  settings:
    build_args_from_env:
      - MYSQL_MAIN_PASSWORD
      - GIT_USERNAME
      - GIT_PASSWORD
    repo: registry.gitlab.com/dadard291/deployer
    registry: registry.gitlab.com
    tags:
      - latest
      - "0.${DRONE_BUILD_NUMBER}"
    username:
      from_secret: gitlab_username
    password:
      from_secret: gitlab_password
  when:
    branch:
      - master
    even:
      - push
