---
kind: pipeline
name: build

platform:
  arch: amd64

steps:
- name: push to registry
  image: plugins/docker
  settings:
    repo: registry.gitlab.com/dadard291/deployer
    registry: registry.gitlab.com
    tags:
      - latest
      - "0.${DRONE_BUILD_NUMBER}"
    username:
      from_secret: gitlab_username
    password:
      from_secret: gitlab_password
  when:
    branch:
      - master
    even:
      - push
